import { chromium } from '@playwright/test';
const url = process.env.PAGE_URL;
if (!url) throw new Error('PAGE_URL is required');
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1180, height: 820 } });
const errors = [];
page.on('pageerror', (error) => errors.push(error.message));
const response = await page.goto(url, { waitUntil: 'networkidle', timeout: 60000 });
if (!response?.ok()) throw new Error(`Page returned ${response?.status() ?? 'no response'}`);
await page.getByRole('heading', { name: 'AI工場ダッシュボード' }).waitFor();
await page.getByRole('heading', { name: 'Study Canvas' }).waitFor();
if (errors.length) throw new Error(`JavaScript errors: ${errors.join('; ')}`);
await page.screenshot({ path: 'live-smoke.png', fullPage: true });
await browser.close();
